name: CI Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-16.04
    name: CI test
    steps:
    - uses: actions/checkout@v2
      name: Checkout repository
      with:
        submodules: 'true'
    - name: Install dependencies
      run: sudo apt-get -y install --no-install-recommends git cmake g++ libgomp1 ninja-build texlive-fonts-recommended texlive-pictures xz-utils
    - name: Build
      run: ./build.sh
    - name: Build LaTeX charts
      run: ninja -C build/ charts/charts_pdf
  docker:
    runs-on: ubuntu-16.04
    name: Docker image creation
    steps:
      - uses: docker/build-action@v1
        name: Docker image build
